name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: "Run test: validate edge cloud clients instantiation"
      run: pytest -v tests/common/test_invoke_edgecloud_clients.py

    - name: "Run test: validate network clients instantiation"
      run: pytest -v tests/common/test_invoke_network_clients.py

  lint:
    name: Run linters
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: isort check
      run: isort src tests --check --profile black --filter-files

    - name: black check
      run: black src tests --check --line-length=100

    - name: flake8 check
      run: flake8 src tests

  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [tests, lint]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install build and upload dependencies
      run: |
        pip install setuptools wheel twine

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
